name: polymer1407
description: A sample Polymer application
dependencies:
  core_elements: any
  paper_elements: any
  polymer: '>=0.11.0-dev.2 <0.12.0'
transformers:
- polymer:
    entry_points:
      - web/index.html
      - web/subdir/index.html
